[package]
name = "edr-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
edr-common = { path = "../edr-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "edr"
path = "src/main.rs"
